name: Playwright Tests with Allure Report and GH Pages Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout коду
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Налаштування Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Встановлення залежностей
      - name: Install dependencies
        run: npm ci

      # 4. Встановлення Playwright браузерів
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Запуск тестів через xvfb-run (для headful браузера)
      - name: Run Playwright tests with Allure reporter
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' npx playwright test --reporter=list,allure-playwright
        continue-on-error: true

      # 6. Встановлення Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline@2.20.1

      # 7. Генерація Allure-репорту
      - name: Generate Allure Report
        run: allure generate ./allure-results --clean -o ./allure-report

      # 8. Деплой Allure-репорту на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
