name: Playwright Tests with Allure Report

# Коли запускати
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Отримати код із репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Встановлюємо Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Крок 3: Встановлення залежностей
      - name: Install dependencies
        run: npm ci

      # Крок 4: Встановлення браузерів Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Крок 5: Запуск тестів з Allure
      - name: Run Playwright tests with Allure reporter
        run: |
          npx playwright test --reporter=list,allure-playwright
          npx allure generate ./allure-results --clean -o ./allure-report

      # Крок 6: Завантажити Allure HTML-репорт
      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
